export enum Polls {
  FETCH_ALL_POLLS = 'FETCH_ALL_POLLS',
  FETCH_ALL_POLLS_OK = 'FETCH_ALL_POLLS_OK',
  FETCH_ALL_POLLS_ERROR = 'FETCH_ALL_POLLS_ERROR',

  POST_POLL = 'POST_POLL',
  POST_POLL_OK = 'POST_POLL_OK',
  POST_POLL_ERROR = 'POST_POLL_ERROR'
}